name: "Rinnai2MQTT"
version: "2.0.6"
slug: "rinnai2mqtt"
description: "Integrates Rinnai water heaters produced in Brazil with Home Assistant via MQTT"
url: "https://github.com/rpr1972/rinnai2mqtt"
startup: "application"
image: "robrosa/rinnai2mqtt"
arch:
  - amd64
  - aarch64
host_network: true
map:
  - config:rw
options:
  mqtt_addr: "127.0.0.1"
  mqtt_user: ""
  mqtt_pass: ""
  device_address: ""
  POLL_INTERVAL: 30
  lock_device_in_use: true
  device_max_temp: 45
schema:
  mqtt_addr: "str"
  mqtt_user: "str?"
  mqtt_pass: "str?"
  device_address: "str"
  POLL_INTERVAL: "int"
  lock_device_in_use: "bool"
  device_max_temp: "int"
