name: "Rinnai2MQTT"
version: "2.0.5"
slug: "rinnai2mqtt"
description: "Integrates Rinnai water heaters produced in Brazil with Home Assistant via MQTT"
url: "https://github.com/rpr1972/rinnai2mqtt"
startup: "application"
image: "robrosa/rinnai2mqtt"
arch:
  - amd64
  - aarch64
host_network: true
map:
  - config:rw
options:
  MQTT_ADDR: "127.0.0.1"
  MQTT_USER: ""
  MQTT_PASS: ""
  DEVICE_ADDR: ""
  POLL_INTERVAL: 30
  LOCK_DEVICE_IN_USE: true
  DEVICE_MAX_TEMP: 45
schema:
  MQTT_ADDR:
    name: "MQTT server address"
    description: "The address of your MQTT broker"
    type: "str"
  MQTT_USER:
    name: "MQTT username"
    description: "Username for MQTT broker authentication (optional)"
    type: "str"
  MQTT_PASS:
    name: "MQTT password"
    description: "Password for MQTT broker authentication (optional)"
    type: "str"
  DEVICE_ADDR:
    name: "Device address"
    description: "The address of the Rinnai water heater"
    type: "str"
  POLL_INTERVAL:
    name: "Default polling interval"
    description: "How often the device status should be checked (in seconds)"
    type: "int"
  LOCK_DEVICE_IN_USE:
    name: "Lock device when in use"
    description: "Whether to lock the device when it's being used"
    type: "bool"
  DEVICE_MAX_TEMP:
    name: "Maximum device temperature"
    description: "The maximum temperature allowed for the device"
    type: "int"
environment:
  MQTT_ADDR: "{{ MQTT_ADDR }}"
  MQTT_USER: "{{ MQTT_USER }}"
  MQTT_PASS: "{{ MQTT_PASS }}"
  DEVICE_ADDR: "{{ DEVICE_ADDR }}"
  POLL_INTERVAL: "{{ POLL_INTERVAL }}"
  LOCK_DEVICE_IN_USE: "{{ LOCK_DEVICE_IN_USE }}"
  DEVICE_MAX_TEMP: "{{ DEVICE_MAX_TEMP }}"
